
POST http://127.0.0.1:8000/backend/login/
Content-Type: application/json

{
    
    "username": "adminerdffdrd",
    "password": "admin"
    
}

###

POST http://127.0.0.1:8000/backend/signup/
Content-Type: application/json

{
    
    "username": "adminerdffdrd",
    "password": "admin",
    "eloReallyBadChess": 2932,
    "eloSecondType": 2932
}