# Generated by Django 5.0 on 2023-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('moves_count', models.PositiveIntegerField()),
                ('challenge_date', models.DateField()),
                ('result', models.CharField(max_length=10)),
                ('attempts', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-moves_count'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('moves_count', models.PositiveIntegerField()),
                ('challenge_date', models.DateField()),
                ('result', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-moves_count'],
            },
        ),
    ]
