# Generated by Django 5.0 on 2023-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_dailyleaderboard_weeklyleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='score_ranked',
            field=models.IntegerField(default=0),
        ),
    ]
