# Generated by Django 5.0 on 2023-12-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_dailyleaderboard_weeklyleaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredusers',
            name='GameDraw',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='GamesLost',
        ),
        migrations.RemoveField(
            model_name='registeredusers',
            name='GamesWon',
        ),
    ]
