# Generated by Django 5.0 on 2023-12-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_multiplayerleaderboard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultiplayerLeaderboard',
        ),
    ]
