# Generated by Django 5.0 on 2023-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_registeredusers_gamedraw_registeredusers_gameslost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyleaderboard',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
