# Generated by Django 5.0 on 2023-12-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiplayerLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("elo", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-elo"],
            },
        ),
    ]
