# Generated by Django 5.0 on 2023-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_multiplayerleaderboard"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MultiplayerLeaderboard",
        ),
        migrations.AlterModelOptions(
            name="dailyleaderboard",
            options={"ordering": ["moves_count"]},
        ),
        migrations.AlterModelOptions(
            name="weeklyleaderboard",
            options={"ordering": ["moves_count"]},
        ),
        migrations.AlterField(
            model_name="dailyleaderboard",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registeredusers",
            name="EloReallyBadChess",
            field=models.IntegerField(default=400),
        ),
    ]
