# Generated by Django 5.0 on 2023-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_delete_multiplayerleaderboard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyleaderboard",
            name="challenge_date",
            field=models.CharField(default="01011970", max_length=8),
        ),
        migrations.AlterField(
            model_name="weeklyleaderboard",
            name="challenge_date",
            field=models.CharField(default="511970", max_length=6),
        ),
    ]
