# Generated by Django 5.0 on 2023-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_delete_multiplayerleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='GameDraw',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='GamesLost',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='registeredusers',
            name='GamesWon',
            field=models.IntegerField(default=1000),
        ),
    ]
