# Generated by Django 5.0 on 2023-12-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_alter_dailyleaderboard_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredusers",
            name="EloReallyBadChess",
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name="registeredusers",
            name="GameDraw",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registeredusers",
            name="GamesLost",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="registeredusers",
            name="GamesWon",
            field=models.IntegerField(default=0),
        ),
    ]
