
POST http://127.0.0.1:8000/backend_django/signup/
Content-Type: application/json

{
    
    "username": "adminerdffdr",
    "password": "admin",
    "eloReallyBadChess": "1500",
    "eloSecondType": "1500"


}