# Generated by Django 4.2.7 on 2023-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0005_alter_registeredusers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredusers',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
