# Generated by Django 4.2.7 on 2023-11-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_django', '0006_registeredusers_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=255)),
                ('username2', models.CharField(max_length=255)),
                ('png', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Games',
            },
        ),
    ]
